docs(docs): setup docs search
rx-angular/rx-angular pull request #1439
Opened 2022-10-14 20:03 UTC by mikelgo

This PR will close #1433 

I setup search using [docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local).

To test it locally you will need to
* `nx run docs:build`
* serve the build docs in the dist folder. Navigate to dist/apps/docs and serve the files e.g. with `npx http-server` (https://github.com/http-party/http-server)

é voilá:
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/29756792/195931894-ffdc7691-075b-44bd-b688-52e6c38dc2dc.png">

In the documentation of the search-plugin there's also an option mentioned on how to have the search available in dev mode  (without serving the build files from a web server) but at least i could not make it work with the nx setup. 

Hint: if you are not serving the build docs from a web server and instead run the project in dev mode with `nx serve docs` you will get a warning when using the search bar:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/29756792/195932359-b3bd679b-64fe-43cd-9ead-9013bbc611cf.png">

2022-10-17 14:30 UTC, LayZeeDK commented
Thank you, @mikelgo! 🙌 This is awesome!

Please rebase on `main` and try it out with the many documentation additions deployed by #1436.

2022-10-17 16:19 UTC, LayZeeDK requested changes
Thank you, @mikelgo! 🙌 This is awesome!

Please rebase on `main` and try it out with the many documentation additions deployed by #1436.

2022-10-17 21:39 UTC, LayZeeDK requested changes

2022-10-17 21:39 UTC, LayZeeDK commented on apps/docs/package.json
> +    "build": "docusaurus build"
issue: We don't need this script since we have `nx build docs`
```suggestion
    "typecheck": "tsc"
```

2022-10-17 22:15 UTC, LayZeeDK commented
@mikelgo 
We have the `serve-static` target for the `docs` project which calls `docusaurus serve` behind the scene. Local search works when using `nx serve-static docs` 👍

2022-10-17 22:24 UTC, LayZeeDK requested changes

2022-10-17 22:24 UTC, LayZeeDK commented on apps/docs/docusaurus.config.js
> +        language: ['en' ],
nit: Leave out the extraneous space.
```suggestion
        language: ['en'],
```

2022-10-18 04:34 UTC, mikelgo commented
> @mikelgo We have the `serve-static` target for the `docs` project which calls `docusaurus serve` behind the scenes. Local search works when using `nx serve-static docs` 👍

Great, thanks for pointing that out 👍

2022-10-18 04:54 UTC, mikelgo commented
@LayZeeDK Thanks for your review, I resolved all the points. 
However I screw up the rebasing with the remote origin, now I have 2 commits.
Originally I wanted to merge the changes from the review in commit c7d9f264c118022904b80f207c3c5271ef3c342f 

maybe you can help me?

2022-10-18 06:23 UTC, LayZeeDK approved these changes
Thank you, @mikelgo. This is a big help to the RxAngular team and the rest of the RxAngular community!

2022-10-18 06:55 UTC, mikelgo commented
Thanks for your kind words @LayZeeDK, really appreciate it. 
I hope I can provide even more helpful things in the future :-)

2022-10-18 07:11 UTC, merged