chore(schematics): add simple-import-sort & unused-imports rules
rx-angular/rx-angular pull request #1560
Opened 2023-05-01 14:00 UTC by Naaajii

this commit installs simple-import-sort & unused-imports eslint rules into workspace

fixes #1548 - add new rules as suggested

2023-05-03 03:15 UTC, hoebbelsB commented
hey @Naaajii , big thanks for your contribution :heart: 

> I have added new rules to the workspace repo, please correct me if I have done anything wrong.

Looks good, let's just configure them as `error`, not as `warn` and run `eslint --fix` afterwards.

> should spec files be included in ignorePatterns?

Let's keep it as is for now

> what should we do with following warnings as they are all over the place:
Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
Empty block statement                     no-empty
'intersectionObserver' is defined but never used  @typescript-eslint/no-unused-vars
remove them? disable them ( tho doing that would be same as doing what we are supposed to in this issue )? fix them one-by-one? I'm sure we can't just fix them by passing --fix as we can for unused imports or sorted imports/exports.

Ignore the warnings for now, we run the lint with `--quiet` to only show errors in the ci pipeline.

> additionally - [eslint-plugin-unused-imports](https://github.com/sweepline/eslint-plugin-unused-imports) comes with no-unused-vars which is same as [@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars). I am unsure what to keep.

Let's only go with one of them. I would suggest to keep `@typescript-eslint/no-unused-vars` in place

2023-05-03 03:16 UTC, hoebbelsB requested changes

2023-05-03 03:16 UTC, hoebbelsB commented on .eslintrc.json
> +        "unused-imports/no-unused-imports": "warn"
let's configure them as `error` and run `nx affected:lint --fix` afterwards :)

2023-05-07 16:44 UTC, edbzn approved these changes

2023-05-07 17:08 UTC, edbzn commented
@Naaajii Can this PR be considered as ready for merge?

2023-05-07 19:39 UTC, Naaajii commented
@edbzn I believe I did implement most of what issue initially mentioned, so yes. however if something looks off let me know after review.

2023-05-09 16:13 UTC, Naaajii commented
i have removed the conflicts so the PR can move forward.

2023-06-04 12:59 UTC, Naaajii commented
aaaaaa, I just rebase and force pushed but conflicts still exists? I might need some help off this. @edbzn

2023-08-18 11:32 UTC, closed without merging