Accept subscribable on rxLet input
rx-angular/rx-angular pull request #1657
Opened 2023-12-08 08:33 UTC by AlirezaEbrahimkhani

resolves #1541

2023-12-08 22:53 UTC, AlirezaEbrahimkhani commented on libs/template/let/src/lib/let.directive.ts
> +  @Input() rxLet: ObservableInput<U> | Subscribable<U> | U | null | undefined;
You're right, I will add test cases for that
thanks for your comment

2023-12-12 17:31 UTC, eneajaho commented
Hello @AlirezaEbrahimkhani Anything you need to move this PR forward?

2023-12-20 08:30 UTC, AlirezaEbrahimkhani commented
@edbzn @eneajaho 
I did the reviews.

2024-01-02 05:13 UTC, AlirezaEbrahimkhani commented
Could you please review this PR?
@eneajaho @edbzn

2024-01-06 12:34 UTC, hoebbelsB commented on libs/template/let/src/lib/tests/let.directive.subscribable.spec.ts
> +  }));
this test doesn't test the `subscribable`. You are essentially overwriting the `BehaviorSubject` with a `number` which is getting rendered.

Instead, you should provide an actual `Subscribable`.

```suggestion
  it('should display value from Subscribable', fakeAsync(() => {
    letDirectiveTestComponent.value$ = {
       subscribe: ({ next }) => {
         next(42)
       }
    };
    fixtureLetDirectiveTestComponent.detectChanges();
    expect(componentNativeElement.textContent.trim()).toBe('42');
  }));
```

2024-01-06 12:49 UTC, hoebbelsB requested changes
as pointed out in the other comment, please adjust the spec so that it actually tests for a subscribable input

2024-02-27 11:44 UTC, hoebbelsB commented
@AlirezaEbrahimkhani any update? :-)

2024-04-14 16:04 UTC, AdrianRomanski commented
@hoebbelsB I'll make it from the scratch on my fork

2024-05-16 21:10 UTC, closed without merging

2024-05-16 21:11 UTC, hoebbelsB commented
close in favor of https://github.com/rx-angular/rx-angular/pull/1721

thank u @AlirezaEbrahimkhani for the initial contribution!