[WIP] feat: add support for application builder and v17 in ISR
rx-angular/rx-angular pull request #1680
Opened 2024-01-23 00:33 UTC by eneajaho

Closes https://github.com/rx-angular/rx-angular/issues/1647

2024-01-25 14:04 UTC, LayZeeDK requested changes
Request change

2024-01-25 14:04 UTC, LayZeeDK commented on libs/isr/package.json
>      "@types/node": "^18.0.0 || ^20.0.0",
Update the lockfile
https://github.com/rx-angular/rx-angular/actions/runs/7619336794/job/20861381969#step:4:166

2024-01-25 14:25 UTC, edbzn reviewed
Nice!

What about e2e testing the `ssr-isr` app with cypress? Just to make sure ISR runs successfully in the CI. Idealy, inlined in the project like we have for the `ssr` app.

I would also suggest squashing the commits at the end.

2024-02-05 14:10 UTC, edbzn approved these changes

2024-02-05 14:13 UTC, merged