feat: rx state as read only
rx-angular/rx-angular pull request #1711
Opened 2024-04-06 12:17 UTC by AdrianRomanski

Fixes #1703

2024-04-06 14:09 UTC, hoebbelsB commented on libs/state/src/lib/rx-state.service.ts
> +  asReadOnly(): Pick<RxState<State>, 'get' | 'select'> {
we of course also want to have the `signal` & `computed` APIs to be exposed.

2024-04-06 14:10 UTC, hoebbelsB commented on libs/state/src/lib/rx-state.service.ts
> +    return this as Pick<RxState<State>, 'get' | 'select'>;
with this approach we only return a new type, the disallowed methods are still available though. It's maybe safer to return a new object, e.g.

```ts
return { get: this.get, select: this.select, computed: this.computed, signal: this.signal }
```

2024-04-06 14:10 UTC, hoebbelsB commented on libs/state/spec/rx-state.service.spec.ts
>      it('should return undefined as initial value', () => {
can u also add dedicated tests for the `readOnly` that check if an error is thrown when trying to write to the readonly state? The apis shouldnt be accessible anymore

2024-04-06 14:13 UTC, hoebbelsB requested changes
hey @AdrianRomanski thank u for the PR <3 very much appreciated. I left some comments with thoughts on the current implementation.

And by any chance, would it be possible to also provide docs for this new behavior? I can assist you with getting familiar with the docs app if you like

2024-04-07 09:04 UTC, AdrianRomanski commented
@hoebbelsB Thanks for the comments :) i will fix them soon. Of course i can provide dosc, will try on my own if got any problem i'll shoot a question :D

2024-04-28 13:22 UTC, hoebbelsB approved these changes
Thank u @AdrianRomanski for the contribution ❤️ just left some comments with fixes for a typo. Looks good otherwise

2024-04-28 13:22 UTC, hoebbelsB commented on apps/docs/docs/state/api/rx-state.md
> +This can be helpful when you don't want other's to write in your state.
```suggestion
This can be helpful when you don't want others to write in your state.
```

2024-04-28 13:22 UTC, hoebbelsB commented on libs/state/src/lib/rx-state.service.ts
> +   * This can be helpful when you don't want other's to write in your state.
```suggestion
   * This can be helpful when you don't want others to write in your state.
```

2024-04-28 15:07 UTC, AdrianRomanski commented
@hoebbelsB fixed the typo and docs building ⌨️

2024-05-03 22:14 UTC, merged