feat(template):detach on complete and error
rx-angular/rx-angular pull request #432
Opened 2020-11-17 22:31 UTC by BioPhoton

2020-11-17 23:08 UTC, hoebbelsB requested changes
this is a very nice idea. but I think we need to move this into a strategy or something. it will lead to problems, when changes from outside should get reflected in those templates.

just a little example:

```html

            <!-- does not work when template gets detached -->
            <ng-container>{{ errorTmplState$ | push }}</ng-container>
            <!-- works fine when template gets detached -->
            <ng-container *rxLet="errorTmplState$; let state">{{ state }}</ng-container>
```

2020-11-18 22:53 UTC, BioPhoton commented
Moved it into the local strategies. I had to extend the work function with the current notification to know the active template

2020-11-20 23:29 UTC, hoebbelsB requested changes
do we really want to have the complete and error templates cold?

2020-11-20 23:29 UTC, hoebbelsB commented on apps/demos/src/app/shared/rx-angular-pocs/render-stragegies/default-strategies.ts
> +  },
so the error and complete template will not receive any changes? don't they receive some context which should get updated?
Also, I think this implementation is very slow, we should store the methods in a map and just call

```ts
notificationWorkMap[notification.kind]();
```

this way we save 1.000s of iterations over the same array again and again.

2020-11-20 23:29 UTC, hoebbelsB commented on apps/demos/src/app/shared/rx-angular-pocs/render-stragegies/model.ts
> +export type RenderWork = <T = unknown>(cdRef: ChangeDetectorRef, context?: any, notification?: RxNotification<T>) => void;
I think this can be quite helpful :)

2020-11-21 00:31 UTC, BioPhoton commented on apps/demos/src/app/shared/rx-angular-pocs/render-stragegies/default-strategies.ts
> +  },
"cold" was confusing at the beginning for me. But got it. 
You mean values from the observable. 

There is no next value after error or complete that could occur from the observable. 
And the triggers for the template has to behave the same. Detach temple and no other CDs affect it. A potential next value will reattach the view.

For the map:
Sure we have to make to nice! Fir the Poc it was important to see what we need to change in the strategy config.

So I will skip any changes on low level implementations.

2020-11-22 13:48 UTC, merged