Polish basics tutorial
rx-angular/rx-angular pull request #645
Opened 2021-04-09 14:55 UTC by hanna-skryl

- [ ] fixed typos
- [ ] adopted class names
- [ ] added comments to the code snippets

2021-04-09 15:03 UTC, BioPhoton requested changes
Hi, @hanna-skryl thanks soo much for this nice PR! ♥
If you could do a small change and move the comments above and also use emojis to highlight the sections and make the whole text visually more appealing.

2021-04-09 15:03 UTC, BioPhoton commented on apps/demos/src/app/features/tutorials/basics/2-input-bindings/input-bindings.start.component.ts
> +      this._refreshInterval = refreshInterval; // Partially update the state with the state slice
If there is a "helper comment" for the person doing the tutorial mostly it's a good idea to put the comment above.
Also a nice thing we can do here is use emoticons to highlight a specific piece of code e.g. 👇
```suggestion
      this._refreshInterval = refreshInterval; // Partially update the state with the state slice
```

2021-04-13 01:30 UTC, hanna-skryl commented
@BioPhoton The pull request has been updated. Please review it at your convenience.

2021-04-13 12:36 UTC, BioPhoton approved these changes

2021-04-13 12:37 UTC, BioPhoton commented
Thanks a lot for this contribution!! <3

2021-04-13 12:37 UTC, merged